version: '3.8'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - DB_PATH=/app/database.db
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.5.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"