apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: zendesk-homework
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4317
            - name: DB_PATH
              value: /app/data/database.db
