apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.5.0
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 5778
            - containerPort: 9411
