// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scorer.proto

package scorer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_proto_scorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_scorer_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ScoreRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ScoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScorePercentage float64                `protobuf:"fixed64,1,opt,name=scorePercentage,proto3" json:"scorePercentage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_scorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_scorer_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreResponse) GetScorePercentage() float64 {
	if x != nil {
		return x.ScorePercentage
	}
	return 0
}

var File_proto_scorer_proto protoreflect.FileDescriptor

const file_proto_scorer_proto_rawDesc = "" +
	"\n" +
	"\x12proto/scorer.proto\x12\x06scorer\"F\n" +
	"\fScoreRequest\x12\x1c\n" +
	"\tstartDate\x18\x01 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x02 \x01(\tR\aendDate\"9\n" +
	"\rScoreResponse\x12(\n" +
	"\x0fscorePercentage\x18\x01 \x01(\x01R\x0fscorePercentage2O\n" +
	"\rScorerService\x12>\n" +
	"\x0fGetOverallScore\x12\x14.scorer.ScoreRequest\x1a\x15.scorer.ScoreResponseB3Z1github.com/siimsams/zendesk-homework/proto;scorerb\x06proto3"

var (
	file_proto_scorer_proto_rawDescOnce sync.Once
	file_proto_scorer_proto_rawDescData []byte
)

func file_proto_scorer_proto_rawDescGZIP() []byte {
	file_proto_scorer_proto_rawDescOnce.Do(func() {
		file_proto_scorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scorer_proto_rawDesc), len(file_proto_scorer_proto_rawDesc)))
	})
	return file_proto_scorer_proto_rawDescData
}

var file_proto_scorer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_scorer_proto_goTypes = []any{
	(*ScoreRequest)(nil),  // 0: scorer.ScoreRequest
	(*ScoreResponse)(nil), // 1: scorer.ScoreResponse
}
var file_proto_scorer_proto_depIdxs = []int32{
	0, // 0: scorer.ScorerService.GetOverallScore:input_type -> scorer.ScoreRequest
	1, // 1: scorer.ScorerService.GetOverallScore:output_type -> scorer.ScoreResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scorer_proto_init() }
func file_proto_scorer_proto_init() {
	if File_proto_scorer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scorer_proto_rawDesc), len(file_proto_scorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scorer_proto_goTypes,
		DependencyIndexes: file_proto_scorer_proto_depIdxs,
		MessageInfos:      file_proto_scorer_proto_msgTypes,
	}.Build()
	File_proto_scorer_proto = out.File
	file_proto_scorer_proto_goTypes = nil
	file_proto_scorer_proto_depIdxs = nil
}
