// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/scorer.proto

package scorer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScorerService_GetAggregatedCategoryScores_FullMethodName    = "/scorer.ScorerService/GetAggregatedCategoryScores"
	ScorerService_GetScoresByTicket_FullMethodName              = "/scorer.ScorerService/GetScoresByTicket"
	ScorerService_GetOverallScore_FullMethodName                = "/scorer.ScorerService/GetOverallScore"
	ScorerService_GetPeriodOverPeriodScoreChange_FullMethodName = "/scorer.ScorerService/GetPeriodOverPeriodScoreChange"
)

// ScorerServiceClient is the client API for ScorerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScorerServiceClient interface {
	GetAggregatedCategoryScores(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*AggregatedCategoryScoresResponse, error)
	GetScoresByTicket(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreByTicketResponse, error)
	GetOverallScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	GetPeriodOverPeriodScoreChange(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*PeriodOverPeriodScoreChangeResponse, error)
}

type scorerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScorerServiceClient(cc grpc.ClientConnInterface) ScorerServiceClient {
	return &scorerServiceClient{cc}
}

func (c *scorerServiceClient) GetAggregatedCategoryScores(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*AggregatedCategoryScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregatedCategoryScoresResponse)
	err := c.cc.Invoke(ctx, ScorerService_GetAggregatedCategoryScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scorerServiceClient) GetScoresByTicket(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreByTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreByTicketResponse)
	err := c.cc.Invoke(ctx, ScorerService_GetScoresByTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scorerServiceClient) GetOverallScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, ScorerService_GetOverallScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scorerServiceClient) GetPeriodOverPeriodScoreChange(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*PeriodOverPeriodScoreChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodOverPeriodScoreChangeResponse)
	err := c.cc.Invoke(ctx, ScorerService_GetPeriodOverPeriodScoreChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScorerServiceServer is the server API for ScorerService service.
// All implementations must embed UnimplementedScorerServiceServer
// for forward compatibility.
type ScorerServiceServer interface {
	GetAggregatedCategoryScores(context.Context, *ScoreRequest) (*AggregatedCategoryScoresResponse, error)
	GetScoresByTicket(context.Context, *ScoreRequest) (*ScoreByTicketResponse, error)
	GetOverallScore(context.Context, *ScoreRequest) (*ScoreResponse, error)
	GetPeriodOverPeriodScoreChange(context.Context, *ScoreRequest) (*PeriodOverPeriodScoreChangeResponse, error)
	mustEmbedUnimplementedScorerServiceServer()
}

// UnimplementedScorerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScorerServiceServer struct{}

func (UnimplementedScorerServiceServer) GetAggregatedCategoryScores(context.Context, *ScoreRequest) (*AggregatedCategoryScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregatedCategoryScores not implemented")
}
func (UnimplementedScorerServiceServer) GetScoresByTicket(context.Context, *ScoreRequest) (*ScoreByTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoresByTicket not implemented")
}
func (UnimplementedScorerServiceServer) GetOverallScore(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOverallScore not implemented")
}
func (UnimplementedScorerServiceServer) GetPeriodOverPeriodScoreChange(context.Context, *ScoreRequest) (*PeriodOverPeriodScoreChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriodOverPeriodScoreChange not implemented")
}
func (UnimplementedScorerServiceServer) mustEmbedUnimplementedScorerServiceServer() {}
func (UnimplementedScorerServiceServer) testEmbeddedByValue()                       {}

// UnsafeScorerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScorerServiceServer will
// result in compilation errors.
type UnsafeScorerServiceServer interface {
	mustEmbedUnimplementedScorerServiceServer()
}

func RegisterScorerServiceServer(s grpc.ServiceRegistrar, srv ScorerServiceServer) {
	// If the following call pancis, it indicates UnimplementedScorerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScorerService_ServiceDesc, srv)
}

func _ScorerService_GetAggregatedCategoryScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorerServiceServer).GetAggregatedCategoryScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScorerService_GetAggregatedCategoryScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorerServiceServer).GetAggregatedCategoryScores(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScorerService_GetScoresByTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorerServiceServer).GetScoresByTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScorerService_GetScoresByTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorerServiceServer).GetScoresByTicket(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScorerService_GetOverallScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorerServiceServer).GetOverallScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScorerService_GetOverallScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorerServiceServer).GetOverallScore(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScorerService_GetPeriodOverPeriodScoreChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorerServiceServer).GetPeriodOverPeriodScoreChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScorerService_GetPeriodOverPeriodScoreChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorerServiceServer).GetPeriodOverPeriodScoreChange(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScorerService_ServiceDesc is the grpc.ServiceDesc for ScorerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScorerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scorer.ScorerService",
	HandlerType: (*ScorerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAggregatedCategoryScores",
			Handler:    _ScorerService_GetAggregatedCategoryScores_Handler,
		},
		{
			MethodName: "GetScoresByTicket",
			Handler:    _ScorerService_GetScoresByTicket_Handler,
		},
		{
			MethodName: "GetOverallScore",
			Handler:    _ScorerService_GetOverallScore_Handler,
		},
		{
			MethodName: "GetPeriodOverPeriodScoreChange",
			Handler:    _ScorerService_GetPeriodOverPeriodScoreChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scorer.proto",
}
